---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.portainer.kubernetes.application.kind: content
    io.portainer.kubernetes.application.name: sonarr
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: sonarr
    io.portainer.kubernetes.application.stackid: "3"
  name: sonarr
  namespace: default
  uid: 8b950832-c987-4dda-a627-70065e012b9e
spec:
  ports:
    - port: 8989
      targetPort: 8989
      nodePort: 30089
  selector:
    app: sonarr
  type: NodePort
status:
  loadBalancer: {}