apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  labels:
    io.portainer.kubernetes.application.kind: content
    io.portainer.kubernetes.application.name: caddy
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: caddy
    io.portainer.kubernetes.application.stackid: '5'
    app: caddy
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  revisionHistoryLimit: 10
  replicas: 1
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 0
  template:
    metadata:
      labels:
        io.portainer.kubernetes.application.kind: content
        io.portainer.kubernetes.application.name: caddy
        io.portainer.kubernetes.application.owner: admin
        io.portainer.kubernetes.application.stack: caddy
        io.portainer.kubernetes.application.stackid: '5'
        app: caddy
        octopusexport: OctopusExport
    spec:
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      volumes:
        - name: app-config
          nfs:
            path: /k3s/
            server: 192.168.1.136
      containers:
        - name: caddy
          image: caddy
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
          volumeMounts:
            - name: app-config
              mountPath: /etc/caddy
              subPath: caddy