---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.portainer.kubernetes.application.kind: content
    io.portainer.kubernetes.application.name: caddy
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: caddy
    io.portainer.kubernetes.application.stackid: "3"
  name: caddy
  namespace: default
  uid: 8b950832-c987-4dda-a627-70065e012b9e
spec:
  clusterIP: 10.43.58.79
  clusterIPs:
    - 10.43.58.79
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: port-0
      port: 8080
      protocol: TCP
      targetPort: 80
    - name: port-1
      port: 8443
      protocol: TCP
      targetPort: 443
  selector:
    app: caddy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
