apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    io.portainer.kubernetes.application.kind: content
    io.portainer.kubernetes.application.name: radarr
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: mediaManagement
    io.portainer.kubernetes.application.stackid: '5'
    app: radarr
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  revisionHistoryLimit: 10
  replicas: 1
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 0
  template:
    metadata:
      labels:
        io.portainer.kubernetes.application.kind: content
        io.portainer.kubernetes.application.name: radarr
        io.portainer.kubernetes.application.owner: admin
        io.portainer.kubernetes.application.stack: mediaManagement
        io.portainer.kubernetes.application.stackid: '5'
        app: radarr
        octopusexport: OctopusExport
    spec:
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      volumes:
        - name: downloads
          nfs:
            path: /volume1/downloads/
            server: 192.168.1.136
        - name: movies
          nfs:
            path: /volume1/plex/movies/
            server: 192.168.1.136
        - name: app-config
          nfs:
            path: /volume1/k3s/
            server: 192.168.1.136
      containers:
        - name: radarr
          image: linuxserver/radarr
          env:
            - name: TZ
              value: Etc/UTC
            - name: PGID
              value: '1000'
            - name: PUID
              value: '1000'
          volumeMounts:
            - name: app-config
              mountPath: /config
              subPath: radarr
            - name: movies
              mountPath: /movies
              subPath: ''
            - name: downloads
              mountPath: /downloads
              subPath: ''
