---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.portainer.kubernetes.application.kind: content
    io.portainer.kubernetes.application.name: radarr
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: mediaManagement
    io.portainer.kubernetes.application.stackid: "3"
  name: radarr
  namespace: default
  uid: 8b950832-c987-4dda-a627-70065e012b9e
spec:
  clusterIP: 10.43.58.77
  clusterIPs:
    - 10.43.58.77
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: port-0
      port: 7878
      protocol: TCP
      targetPort: 7878
  selector:
    app: radarr
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
