---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.portainer.kubernetes.application.kind: content
    io.portainer.kubernetes.application.name: radarr
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: radarr
    io.portainer.kubernetes.application.stackid: "3"
  name: radarr
  namespace: default
  uid: 8b950832-c987-4dda-a627-70065e012b9e
spec:
  ports:
    - port: 7878
      targetPort: 7878
      nodePort: 30078
  selector:
    app: radarr
  type: NodePort
status:
  loadBalancer: {}
