apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels:
    io.portainer.kubernetes.application.kind: content
    io.portainer.kubernetes.application.name: jackett
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: jackett
    io.portainer.kubernetes.application.stackid: '5'
    app: jackett
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  revisionHistoryLimit: 10
  replicas: 1
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 0
  template:
    metadata:
      labels:
        io.portainer.kubernetes.application.kind: content
        io.portainer.kubernetes.application.name: jackett
        io.portainer.kubernetes.application.owner: admin
        io.portainer.kubernetes.application.stack: jackett
        io.portainer.kubernetes.application.stackid: '5'
        app: jackett
        octopusexport: OctopusExport
    spec:
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      volumes:
        - name: app-config
          nfs:
            path: /volume1/k3s/
            server: 192.168.1.136
      containers:
        - name: jackett
          image: linuxserver/jackett
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TZ
              value: Etc/UTC
            - name: AUTO_UPDATE
              value: 'true'
          volumeMounts:
            - name: app-config
              mountPath: /config
              subPath: jackett